### ISSUE TITLE
Derive estimates on top-down algorithms based on 2-level cuts

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#165]
We can further improve on the bounds in #98 by using the idea of _i_-level cuts.

> *Definition*: An _i_-level cut of a BDD for _f_ is a cut (S,T) of its DAG _G<sub>f</sub>_, where there exists some _j_ such that nodes in _S_ have a label _l < j+i_ and nodes in _T_ have a label _l > j_.

Here is a picture for intuition:

![IMG_20211105_123538_6](https://user-images.githubusercontent.com/14313096/140504724-d5881a5c-49c6-4723-bd0d-63b47df7e1c9.jpg)

Notice, how this cut looks like the state of the priority queue!

In #266 , #267 and #269 we make sure to be able to compute both the *1-level* and the *2-level* cuts of the input DAG. Furthermore, with #268 we also have the number of arcs to each sink.

# Worst-case bounds based on cuts

The upper bounds below are probably in most cases tighter than what was given in #98 , but we want to keep both and take the _minimum_ of the two, such that we have the tightest of the two. We can add to the statistics, how many times one won over the other.

## Unary input algorithms

These algorithms traverse top-down the one BDD, and so the size of their priority queues is at most the maximal 2-level cut of the input BDD. 

### Count

- [ ] **C<sub>f:2</sub>**

### Substitution

- [ ] **C<sub>f:2</sub>**

Remember, that we still need the +2 (assuming #150 is not solved)

### Intercut

About the new nodes we notice, that their children are either to a sink or to the very _target_ of the arc that was cut. So, about the output and the algorithm's behaviour we can conclude that:

- Always at most two copies exist of the same arc of the input. At worst, it can point to the _target_ twice or to the _target_ and to a cuttable sink.
- The arcs to _true_ only exist (possibly doubled) if `intercut_policy::cut_true_sink` is true
- The arcs to _false_ only exist (possibly doubled) if `intercut_policy::cut_false_sink` is true
- Nodes cutting the _true_ / _false_ sink only have _sink_ children (but they may be somewhat intertwined)

With some extra analysis we can in fact identify the times where the "possibly doubled" does not apply. That is, the bound for **both** priority queues is:

- [ ] 2 C<sub>f:2</sub> + 2 S<sub>T</sub> + 2 S<sub>F</sub>

Where S<sub>T</sub> and S<sub>F</sub> are the number of sinks with either value. As stated above, they should only be part of this sum, if the policy wants to cut those sink arcs.

**TODO**: This is not entirely correct. The _complement_ function flips the sink value which also here flips which type of sink should be counted. I wonder whether we can identify such a case with a predicate on the strategy?

## Product Construction algorithms

For simplicity, let's focus on the Apply algorithm. The argumentation below should be extensible to the if-then-else, quantification, and other procedures.

### Apply

Here, **including** arcs to sinks we have

- [ ] **C<sub>f:2</sub> · C<sub>g:2</sub>**

Here, similar to #167 we can ignore on either side any arcs to sinks that shortcut recursion. Also remember, that we still need the +2 (assuming #150 is not solved)

### Quantification

Here, **without** including any sinks we have

- [ ] **C<sub>f:2</sub><sup>2</sup>**

Remember, that we still need the +2 (assuming #150 is not solved)

Note, since we are pairing the cut with itself, then we also pair the arc with itself. Hence, this product **also** includes simulating the input BDD and we do not need a '+ C<sub>f:2</sub>' term

### If-Then-Else

Here, **including** arcs to sinks we have

- [ ] **C<sub>f:2</sub> · C<sub>g:2</sub> · C<sub>h:2</sub>**

Remember, that we still need the +2 (assuming #150 is not solved).
