### ISSUE TITLE
Fine-grained control of type of per-level sorters in Reduce

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#169]
The Reduce algorithm initialises and uses for each level two *external_sorter*s which are a thin wrapper of TPIE's `tpie::merge_sorter`. Yet, we know that at most **N<sub>i<sub>** (the number of nodes of the input's *i*th level, which is given in the meta information) are going to be sorted. So, we can exploit the cases where all **N<sub>i<sub>** elements of **both** sorters fits into internal memory!

**Tasks**

- [x] Move the entire inner logic for each level into a templated function `reduce_level<dd_policy, sorter_t>`.
- [x] Add the `adiar::internal_sorter` class as an alternative to the `adiar::external_sorter` in *adiar/internal/sorter.h*. Both of these should have the exact same interface for its constructor and methods (possibly ignoring some input arguments).
   - Internally it uses the `tpie::internal_vector` and `std::sort` (see the experiments in #98 for this specific choice)
   - The *internal_sorter* should lift the `memory_usage` and `memory_fits` functions from the `tpie::internal_vector` to allow computing whether it will fit into memory. 
- [x] Switch between calling `reduce_level<dd_policy, external_sorter` and `reduce_level<dd_policy, internal_sorter` depending on whether `internal_sorter::memory_fits(available_memory / 2)) / 2` is larger than the size of the level.
   - Notice, one needs to take the memory used by the temporary file for the first reduction rule into account! ( Fix with #244 )
   - If we want to be fancy and not open another *level_info_stream*, then can let the *levelized_priority_queue* give access to an upper bound on the requests for a level. This would require some MAX_UINT64 dummy value for when the levels are given as a *label_file*.
