### ISSUE TITLE
Allow user to force exclusive internal memory usage

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#255]
Simon Wimmer ( @wimmers ) suggested we allow the user to override all of our upper bounds in this [milestone](https://github.com/SSoelvsten/adiar/milestone/7) to always force one to use internal (or external) memory.

- [x] Add the following enum type in *adiar/internal/memory.h*
       ```cpp
       enum mode
       {
          AUTO,
          INTERNAL,
          EXTERNAL
       }
       ```
       and then add a `mode` global variable with the default value being `AUTO`.
- [x] If `memory::mode != memory::mode:AUTO` then we run some extra logic:
      - `INTERNAL`: the upper bound is decreased to the maximum possible before branching.
      - `EXTERNAL`: shortcuts the branch deciding what version to execute.

**Tasks**
   - [x] *adiar/internal/count.h*
   - [x] *adiar/bdd/if_then_else.cpp*
   - [x] *adiar/internal/intercut.h*
   - [x] *adiar/internal/pred.h*
   - [x] *adiar/internal/product_construction.h*
   - [x] *adiar/internal/quantification.h*
   - [x] *adiar/internal/reduce.h*
   - [x] *adiar/internal/substitution.h*
