### ISSUE TITLE
Add number of arcs to sinks as meta information

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#268]
Some of our more complicated bounds rely on knowing the number of *true* and *false* sinks in the input, e.g. *intercut*.

- [x] Add two variables with type *size_t* in *__meta_file* with the number of *true* and *false* sinks.
- [x] Derive this value inside of the `node_writer`'s push method. Here, you can use a simple
    ```cpp
    true_sinks += (is_sink(n.low) && value_of(n.low)) + (is_sink(n.high) && value_of(n.high))
    false_sinks += (is_sink(n.low) && !value_of(n.low)) + (is_sink(n.high) && !value_of(n.high))
    ```
- [x] Make the *arc_writer* class update the value when pushing sinks 
- [x] Change unit tests to test correct number of sinks in all algorithms (not Reduce)
- [x] Derive this value in `reduce` by the same computations above for every node *n* put into the output.
- [x] Change unit tests for Reduce to test the correct number of sinks
- [x] Fail-fast in *is_isomorphic* (*internal/pred.cpp*) based on a mismatch in the number of sinks.
   - [x] Add unit tests for all the possible ways of hitting this case! If any current unit tests already hit them, then we need to change them to still test for the same thing as before.
   - [x] Add statistics on hitting this case (no need to differentiate between the two sink values)

**Comment by AnnaBlume99** [comment]
Hvordan tilgår jeg __meta_file inde fra node_writer? 
Og jeg kan ikke finde en klasse der hedder sink_arc_writer - kun arc_writer

**Comment by SSoelvsten** [comment]
1. En `node_writer` skulle gerne have en `std::shared_ptr` nedarvet fra sin `meta_file_writer`.
2. True, jeg blandede det sammen med `sink_arc_stream` . Jeg mente `unsafe_push_sink` funktionen på `arc_writer`
