### ISSUE TITLE
Move `reduce` taint flag out of `e.target()`

### ISSUE THREAD

**Issue by ssoelvsten** [SSoelvsten/adiar#412]
We ought to move the *taint* flag from the `e.target().is_flagged()` into a separate `e.flags[REDUCE_FLAG::CUT_TAINT]`. This provides the basis for us to add many of the extensions.

- For #433, we need to free the current flag to be used for the complementation flag.
- #434 requires forwarding the hash of the children.
- #435 requires knowing the variable describing the node and describing its children.

**Tasks**

- [ ] Define `reduce_arc` type to publicly inherit from `arc` 
- [ ] Add private `uint8_t flags` variable and a `flag(enum)` function to access it. Add `set_flag(enum)` to set the flag.
- [ ] Replace usage of the flagging on *target* with using the flag.

**Comment by SSoelvsten** [comment]
It seems like this might be useful for Nested Sweeping, if one wants to make it support the output of the inner sweep are *above* the outer one. This makes the *Relational Product*, *Multi-composition* ( #411 ), and *Variable Reordering*. Because, here we can add a *CURRENT_SWEEP* flag that dictates whether to forward the edge in the current sweep or in the parent sweep.

**Comment by SSoelvsten** [comment]
While the goal itself of moving the taint flag is done, the resulting class `reduce_flags` should be generalised into a tuple of `bool` in *adiar/internal/data_types*.

**Comment by SSoelvsten** [comment]
See #479 for a reference implementation. But, it probably needs to be fully reimplemented from scratch to deal with the merge conflicts.
