### ISSUE TITLE
Turn `assignment` into a class

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#419]
Follow-up on #397 where all the internal data types have been updated to be (immutable) classes.

**Tasks to turn `assignment` into a class**

- [x] Replace `struct` with `class`.
- [x] Move `value_of(assignment&)` into a being a member function `value()`.
- [x] Move `label_of(assignment&)` into being a member function `label()`.
- [x] Add `level()` member function which is a light wrapper on `label()`.

**Tasks to Generalise Usage**

- [x] Add *value_t* enum with values: *FALSE (0), TRUE (1), NONE (-1)* and change the *value* to be of this type.
  - [x] Update the logic in `bdd_restrict` accordingly.
    - [x] Remove the `substitute_act` in favour of the new *assignment::value_t*
  - [x] Update the logic  in `bdd_eval` and `zdd_elem` as needed.

Also, of course remember to update all unit tests and expand on them as needed.
