### ISSUE TITLE
Add BDD width to `node_file`

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#461]
I believe we can make interesting use of the BDD's width, i.e. the maximum size over all its levels.

**Tasks**

We need to do the following to obtain the width as a number.

- [x] **Add to `node_file`**
  Add the `width` variable to the *node_file* stats struct. Then add the computation of this value in the following algorithms (plus include the unit tests)
  - [x] *internal/algorithms/reduce.h*
  - [x] *internal/algorithms/build.h*
  - [x] *bdd/build.cpp*
  - [x] *zdd/build.h*

  It also needs to be added to the Node Writer class (and by extension the Builder classes)
  - [x] *internal/io/node_writer.h*
  - [x] *build.h*

**Comment by SSoelvsten** [comment]
I moved the additional usage of the width within the isomorphism algorithm into its own issue.
