### ISSUE TITLE
Extend `quantify` with partial quantification

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#501]
Currently, the `quantify` sweep can only take care of a single variable at a time. Yet, if we have a *label predicate* ( #147 ), we can also quantify each variable partially. Running this *n* times would then still (correctly) quantify all *n* variables. But, one could hope, we can do it in fewer sweeps.

**Tasks**

- [x] Do #482 for *quantify*.
- [x] Change the quantification sweep logic to be based being given a `policy_impl` (instance of *quantify_policy*)
  - The `quantify(dd, i, op)` then merely wraps *i* into a `quantify_level(j) { return j == i; }` predicate.
  - The `quantify(dd, gen, op)` and `quantfy(dd, pred, op)` that use Nested Sweeping (#499) merely use an always-false (known at compile-time) predicate.
- [x] Extend the quantification sweep to support having the predicate become true multiple times. Here, we keep on simulating a product, but restart a quantification if it collapses back into a single node.
  - [x] Abuse the fact that the order does not matter: (a) merge duplicates across the *low* and *high* arcs and (b) prune away irrelevant terminals. Only output a node, if the number of nodes that survived were larger than two.
- [x] Replace the transposition step in `quantify(dd, pred, op)` with a single variable quantification with one partial quantification.
- [x] Create a new `node_stream` class designed for an *arc file* which can provide a top-down sweep access with nodes for unreduced outputs. Use this for possibly doing multiple partial quantifications (as long as the result does not grow too large).
