### ISSUE TITLE
Extend `bdd_satmin` and `bdd_satmax` with Domain

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#504]
Many of these additions can also be extended to the *cube* operations in #454 .

The output of the `bdd_satmin(f)` and `bdd_satmax(f)` only (and always) include the variables mentioned within the given BDD *f*. Yet, what if the user is working over some domain larger than the levels in the BDD? Then semantically (a) it consist of more than one assignment and (b) `bdd_satmax` does not provide per-se the largest since some variables may be left out.

**Tasks**

- [x] Use the *domain* (if it exists) as default rather than the BDD's own levels (:warning: *breaking(ish)!*)
- [ ] Only use the *domain* (if it exists) if it actually is a superset of the BDD's levels.

**Additional Features**

The following are in conflict with #225 , which would take precedence over this (considering the user wants an output).

- [ ] Extend to `bdd_satmin(f, ...)` and `bdd_satmax(f, ...)` to be given a set of variables. 
  - [ ] With a generator function that provides the domain in ascending order. This may be a sub or a superset of the variables (or a bit of both).
  - [ ] With an iterator which is also wrapped into a generator function.

**Comment by SSoelvsten** [comment]
For the non-breaking half, we need about it, since it is in conflict with #225 and specifying the domain is not often of interest. Yet, the iterators in #255 seem more useful.

**Comment by SSoelvsten** [comment]
Considering other BDD packages, we should maybe reconsider removing what new features we already have added of the above.
