### ISSUE TITLE
Improve legibility of `bdd_support` (earlier `bdd_varprofile`)

### ISSUE THREAD

**Issue by ssoelvsten** [SSoelvsten/adiar#552]
It is not clear, that Adiar has support to obtain all variables in a BDD or ZDD.

**Tasks**:

- BDD:
  - [x] Move `bdd_varprofile` up next to `bdd_minvar` and `bdd_maxvar` in the BDD API.
  - [x] Rename `bdd_varprofile` into `bdd_support`.
  - [ ] Add a new overload `bdd_support(f)` that returns a `bdd` cube (see also: #533).
- ZDD:
  - [x] Move `zdd_varprofile` up next to `zdd_minvar` and `zdd_maxvar` in the ZDD API.
  - [x] Rename `zdd_varprofile` into `zdd_support`.
  - [ ] Add a new overload `zdd_support(A)` that returns a `zdd` point (blocked until #571 is resolved).

**Additional context**
This was noticed by Anna Blume Jakobsen while browsing through the documentation.

**Comment by SSoelvsten** [comment]
Doing this, we can also add `bdd_varprofile` in the way it is used in BuDDy, i.e. where you get to read through the levels file.
