### ISSUE TITLE
Local Search Heuristics

### ISSUE THREAD

**Issue by ssoelvsten** [ssoelvsten/adiar#560]
With #500 we have an asymptotically efficient (and hopefully in practice also great) way to compute the result of a different variable reordering. This we can use as the backbone for a dynamic variable reordering procedure

**Tasks**

- [ ] Add early termination in `dd_replace` if the size begins to exceed some threshold (1+ɛ) of the input size (ɛ specified in the `exec_policy` or as an optional last argument). This way we can guarantee, that our algorithm never uses more than O(N) space as we treat those cases as having infinite size.

     To do so, add into Nested Sweeping a test on whether the returned `__dd` from the nested sweep is a `no_file`. Then, add this bail-out to `dd_bubble`.

- [ ] Implement `dd_reorder`. Here, we especially should think about one of the following heuristics.
  - [Simulated Annealing](https://en.wikipedia.org/wiki/Simulated_annealing)
  - [Genetic Algorithm](https://en.wikipedia.org/wiki/Genetic_algorithm)
  - [Ant Simulation](https://en.wikipedia.org/wiki/Ant_colony_optimization_algorithms)

  See Sølvsten's thesis [*Sølvsten25*] for more details on the above heuristics.

**Nice-to-Haves**

- [ ] Add early termination in `dd_reorder` if a maximum running time is exceeded (also specified in the `exec_policy`).

- [ ] Extend `dd_reorder` to optimize the combined size of multiple BDDs.

### References

- [[Sølvsten25](https://ssoelvsten.github.io/publications/2025.phd_thesis.pdf)] S. Sølvsten “*I/O-efficient Symbolic Model Checking*”. Aarhus University (2025)

**Comment by SSoelvsten** [comment]
- [ ] One can improve performance by only transposing the given BDD once and then reusing the transposed BDD.
